# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/centos-6.8"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "../go", "/var/go", :mount_options => ["dmode=777,fmode=777"]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.boot_timeout = 600

  config.vm.provision "chef_solo" do |chef|
    cookbooks_path = ["cookbooks"]
    nodes_path = []
    roles_path = ["common"]
  end

  #プラグインの動作設定
  config.omnibus.chef_version = 12
end
